version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: resiliocart_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resiliocart
    ports:
      - "5432:5432"
    volumes:
      - resiliocart_pgdata:/var/lib/postgresql/data

volumes:
  resiliocart_pgdata:
